In [1]:
# 1. Import Numpy 
# 2.Create an array of 10 zeros 
# 3.Create an array of 10 ones 
# 4.Create an array of the integers from 10 to 50
# 5.Create an array of all the even integers from 10 to 50
# 6.Create a 3x3 matrix with values ranging from 0 to 8
# 7. Create a 3x3 identity matrix
# 8. use NumPy to generate a random number between 0 to 1
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution 
# 10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1 
# 11. Create an array of 20 linearly spaced points between 0 and 1
# 12.Create a 5x5 matrix as 
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])
# 	find following using slicing
# 	a.       array([[12, 13, 14, 15],
#       		      [17, 18, 19, 20],
#                       [22, 23, 24, 25]])
# 	b. 20
# 	c.array([[ 2],
#       		 [ 7],
#        		 [12]])
# 	d.array([21, 22, 23, 24, 25])
# 	e.array([[16, 17, 18, 19, 20],
#                 [21, 22, 23, 24, 25]]) 
# 13. Get sum of all values in matrix
# 14. Get sum of all the columns in matrix
# 15. Get Standard deviation , varience , minimum, maximum from matrix row wis.
# 16. create 2 d matrix with all border values nan and 


In [2]:
import numpy as np

In [3]:


#2.Create an array of 10 zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3.Create an array of 10 ones 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# 4.Create an array of 10 to 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# 5.Create an array of the integers from 10 to 50 even number
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [7]:
#6.Create a 3x3 matrix with values ranging from 0 to 8
ar=np.arange(9)
ar.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#  7. Create a 3x3 identity matrix
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 8. use NumPy to generate a random number between 0 to 1
np.random.rand()

0.9485039801405404

In [10]:
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution 
np.random.rand(25)

array([0.28721419, 0.48358796, 0.95728429, 0.99786144, 0.31759218,
       0.83238583, 0.45532792, 0.17167284, 0.33843454, 0.88966607,
       0.23938769, 0.59015053, 0.41891451, 0.89325689, 0.32384191,
       0.11628686, 0.75439942, 0.71830462, 0.3317402 , 0.73300209,
       0.83892622, 0.83456838, 0.22068164, 0.88326536, 0.59105876])

In [11]:
# 10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1 
ar=np.arange(0.01,1.01,0.01)
ar.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [12]:
# 11. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
# 12.Create a 5x5 matrix as 
# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])


ar =np.arange(1,26).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
#find following using slicing
# 	a.       array([[12, 13, 14, 15],
#       		      [17, 18, 19, 20],
#                       [22, 23, 24, 25]])
ar[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# 	b. 20
ar[3:4,4:]

array([[20]])

In [16]:
# 	c.array([[ 2],
#       		 [ 7],
#        		 [12]])
ar[:,1]

array([ 2,  7, 12, 17, 22])

In [17]:
# 	d.array([21, 22, 23, 24, 25])
ar[4:]

array([[21, 22, 23, 24, 25]])

In [18]:
#e.array([[16, 17, 18, 19, 20],
#                 [21, 22, 23, 24, 25]]) 

ar[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
#Get sum of all values in matrix
ar.sum()

325

In [20]:
# 14. Get sum of all the columns in matrix
ar.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
# 15. Get Standard deviation , varience , minimum, maximum from matrix row wis.
ar



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
ar.std(axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [23]:
ar.var(axis=1)

array([2., 2., 2., 2., 2.])

In [24]:
ar.min(axis=1)

array([ 1,  6, 11, 16, 21])

In [25]:
ar.max(axis=1)

array([ 5, 10, 15, 20, 25])

In [26]:
# 16. create 2 d matrix with all border values nan and 
ar =np.arange(0,16,dtype=float).reshape(4,4)

ar
ar[0]=np.nan
ar[3]=np.nan
ar[:,0]=np.nan
ar[:,3]=np.nan
ar

array([[nan, nan, nan, nan],
       [nan,  5.,  6., nan],
       [nan,  9., 10., nan],
       [nan, nan, nan, nan]])

In [27]:
# 1. Create 1-D, 2-D and 3-D numpy array
# 2. Print data type of array.
# 3. Print shape and dimensions of all the three different array.
# 4. Create another 1-D array of 12 elements filled with zero
# 5. Create another 2-D array elements filled with ones.
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.
# 7. Sort the above array in ascending and descending order.
# 8. Create a copy of sorted array to another variable by deep copying.
# 9. Create 2-D array of 5x5 which is an identity matrix and then convert t+

# 10. Create 2-D array of 3x3. Add one more row to it.
# 11. Split above array created vertically and horizontally.
# 12. Create 4x4 identity matrix. Add 4 to each element.
# 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal’s).
# 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.
# 15. Create a null vector of size 10 with 6th value filled with 200.
# 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
# 17. Reverse the above vector.
# 18. Create a 5x5 matrix with values ranging from 0-24 using some function.
# 19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
# 20. Create a 10x10 matrix with 1 on the borders and 0 inside.
# 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
# 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction

In [28]:
# 1. Create 1-D, 2-D and 3-D numpy array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
a=np.arange(16).reshape(4,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [31]:
# 2. Print data type of array.
a.dtype

dtype('int32')

In [32]:
# 3. Print shape and dimensions of all the three different array.
a.shape

(4, 2, 2)

In [33]:
a.ndim

3

In [34]:
# 4. Create another 1-D array of 12 elements filled with zero


In [35]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
# 5. Create another 2-D array elements filled with ones

In [37]:

np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

In [38]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.

In [39]:
marks=np.random.randint(0,100,20)
marks

array([22, 21, 22, 59, 66, 75, 56, 47, 19, 57, 97, 54,  8, 53, 50, 77, 24,
       58,  8, 82])

In [40]:
# 7. Sort the above array in ascending and descending order.
asc=np.sort(marks)
asc


array([ 8,  8, 19, 21, 22, 22, 24, 47, 50, 53, 54, 56, 57, 58, 59, 66, 75,
       77, 82, 97])

In [41]:
np.flip(asc)

array([97, 82, 77, 75, 66, 59, 58, 57, 56, 54, 53, 50, 47, 24, 22, 22, 21,
       19,  8,  8])

In [42]:
# 8. Create a copy of sorted array to another variable by deep copying.
deepCopy =np.copy(asc)
deepCopy


array([ 8,  8, 19, 21, 22, 22, 24, 47, 50, 53, 54, 56, 57, 58, 59, 66, 75,
       77, 82, 97])

In [43]:
# 9. Create 2-D array of 5x5 which is an identity matrix and then convert t+
np.eye(5,5).reshape(25)


array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [44]:
# 10. Create 2-D array of 3x3. Add one more row to it.
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.append(a,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
# 11. Split above array created vertically and horizontally.
np.vsplit(a,3)




[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [47]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [48]:
# 12. Create 4x4 identity matrix. Add 4 to each element.
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [49]:
# 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal’s).
a=np.random.uniform(1,20,5)
a


array([17.35194559,  4.70183121, 16.50218665,  4.81488899, 16.65444898])

In [50]:
np.ceil(a)




array([18.,  5., 17.,  5., 17.])

In [51]:
np.floor(a)

array([17.,  4., 16.,  4., 16.])

In [52]:
np.round(a,2)

array([17.35,  4.7 , 16.5 ,  4.81, 16.65])

In [53]:
# 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.
a=np.arange(0,25).reshape(5,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
np.min(a,axis=0)

array([0, 1, 2, 3, 4])

In [55]:
np.max(a,axis=0)

array([20, 21, 22, 23, 24])

In [56]:
np.std(a,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [57]:
# 15. Create a null vector of size 10 with 6th value filled with 200.
a=np.arange(1,10,dtype=float)
a[:]=np.nan
a[5]=200
a


array([ nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [58]:
# 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.
a=np.arange(100,151)
a


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [59]:
# 17. Reverse the above vector.
np.flip(a)


array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [60]:
# 18. Create a 5x5 matrix with values ranging from 0-24 using some function.
np.arange(25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
#19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
np.mat([1,0,2,0,0,4,0,8])


matrix([[1, 0, 2, 0, 0, 4, 0, 8]])

In [62]:
# 20. Create a 10x10 matrix with 1 on the borders and 0 inside.
a=np.ones(100).reshape(10,10)
a[1:9,1:9]=0
a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
# 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
a=np.ones(64).reshape(8,8)
a[1::2,::2]=0
a[::2,1::2]=0
a


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [64]:
# 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction
a=np.random.randint(0,9,9).reshape(3,3)
b=np.random.randint(0,9,9).reshape(3,3)
a


array([[0, 4, 4],
       [0, 8, 1],
       [5, 7, 6]])

In [65]:
b

array([[3, 6, 4],
       [8, 5, 3],
       [2, 5, 1]])

In [66]:
np.add(a,b)

array([[ 3, 10,  8],
       [ 8, 13,  4],
       [ 7, 12,  7]])

In [67]:
np.multiply(a,b)

array([[ 0, 24, 16],
       [ 0, 40,  3],
       [10, 35,  6]])

In [68]:
np.subtract(a,b)

array([[-3, -2,  0],
       [-8,  3, -2],
       [ 3,  2,  5]])

In [69]:
#lab 5
#task-1
# 1. Create 3 list viz. productId, Product Name, Product Price with 5 elements each.
# Add this element to create a DataFrame.
# 2. Extract one by one column and display separately from above dataframe.
# 3. Display separately each and every row from an above dataframe. (use loc or iloc function)
# 4. Display product name from 3 row using loc function.
# 5. Display price located in 2 row using iloc function.
# 6. Display 2nd to 4th row data excluding price.
# 7. Display 1 to 3rd row price data only.
# 8. Change marks in python column to 41 for students who have scored less than 40.
# 9. Add 2 marks to all the subjects marks. If any of the marks exceeds 100 change it to 100.
# 10. Display students who have scored more than 50 marks in python and more than 60 marks in data
# Science.
# 11. Display students records whose name starts with letter S.
# 12. Display students records whose name ends with letter a.
# 13. Calculate total and percentage for all the students.
# 14. Calculate Status (PASS / FAIL) for the Students.
# 15. Calculate percentage based grade value (per>=90 then A-grade, per>=80 then B-grade,
# per>=70 then C-grade, per>=60 then D-grade, per>=50 then E-grade, per<50 then Fgrade)
# 16. Also calculate overall columns total, maximum, minimum and standard deviation for each
# numeric columns
# Convert the above dataframe to excel, json and html.
# 17. Display meta-data for each column for the above dataframe.
# 18.Convert the above DataFrame to list within a dictionary.
# 19. Convert this dictionary again to a separate dataframe by adding 500 to each element in product 

In [70]:
import pandas as pd

In [71]:
# 1. Create 3 list viz. productId, Product Name, Product Price with 5 elements each.
ProductsDetails = [(10,"Shampoo",100),
                   (20,"TootPaste",60),
                   (30,"brush",110),
                   (40,"Tub",90),
                  (50,"Bench",150)]

a=pd.DataFrame(ProductsDetails,columns=["productId", "Product Name", "Product Price"])
a

productId Product Name  Product Price
0         10      Shampoo            100
1         20    TootPaste             60
2         30        brush            110
3         40          Tub             90
4         50        Bench            150

In [72]:
# 2. Extract one by one column and display separately from above dataframe.
a["productId"]

0    10
1    20
2    30
3    40
4    50
Name: productId, dtype: int64

In [73]:
a["Product Name"]


0      Shampoo
1    TootPaste
2        brush
3          Tub
4        Bench
Name: Product Name, dtype: object

In [74]:
a["Product Price"]

0    100
1     60
2    110
3     90
4    150
Name: Product Price, dtype: int64

In [75]:
# 3. Display separately each and every row from an above dataframe. (use loc or iloc function)
a.loc[0]

productId             10
Product Name     Shampoo
Product Price        100
Name: 0, dtype: object

In [76]:
a.loc[1]

productId               20
Product Name     TootPaste
Product Price           60
Name: 1, dtype: object

In [77]:
a.loc[2]

productId           30
Product Name     brush
Product Price      110
Name: 2, dtype: object

In [78]:
a.loc[3]

productId         40
Product Name     Tub
Product Price     90
Name: 3, dtype: object

In [79]:
a.loc[4]

productId           50
Product Name     Bench
Product Price      150
Name: 4, dtype: object

In [80]:
# 4. Display product name from 3 row using loc function.
a
a.loc[3:]

productId Product Name  Product Price
3         40          Tub             90
4         50        Bench            150

In [81]:
# 5. Display price located in 2 row using iloc function.
a.iloc[1]["Product Price"]


60

In [82]:
# 6. Display 2nd to 4th row data excluding price.
a.iloc[1:4,0:2]


productId Product Name
1         20    TootPaste
2         30        brush
3         40          Tub

In [83]:
# 7. Display 1 to 3rd row price data only.
a.loc[:4]["Product Price"]
 

0    100
1     60
2    110
3     90
4    150
Name: Product Price, dtype: int64

In [84]:
# 8. Change marks in python column to 41 for students who have scored less than 40.


a=pd.DataFrame(np.random.randint(0,100,(4,3)),index=["Matin","Yash","Kuldeep","Jay"],columns=["DSA","Python","Net"])
a


DSA  Python  Net
Matin     28      96   48
Yash       4      69   50
Kuldeep   49      59   74
Jay       10      89   51

In [85]:
a.loc[a["Python"]<40,"Python"]=41
a

DSA  Python  Net
Matin     28      96   48
Yash       4      69   50
Kuldeep   49      59   74
Jay       10      89   51

In [86]:
# 9. Add 2 marks to all the subjects marks. If any of the marks exceeds 100 change it to 100.
a.add(2)


DSA  Python  Net
Matin     30      98   50
Yash       6      71   52
Kuldeep   51      61   76
Jay       12      91   53

In [87]:
# 10. Display students who have scored more than 50 marks in python and more than 60 marks in data
a[(a["Python"]>50) & (a['DSA']>60)]



Empty DataFrame
Columns: [DSA, Python, Net]
Index: []

In [88]:
# 11. Display students records whose name starts with letter S.
a[a.index.str.startswith("M")]


DSA  Python  Net
Matin   28      96   48

In [89]:
# 12. Display students records whose name ends with letter a.
a[a.index.str.endswith("y")]



DSA  Python  Net
Jay   10      89   51

In [90]:
# 13. Calculate total and percentage for all the students.


In [91]:
a['Total']=a["DSA"]+a["Python"]+a["Net"]
a

DSA  Python  Net  Total
Matin     28      96   48    172
Yash       4      69   50    123
Kuldeep   49      59   74    182
Jay       10      89   51    150

In [92]:
a["Perc"]=a["Total"]/3
a

DSA  Python  Net  Total       Perc
Matin     28      96   48    172  57.333333
Yash       4      69   50    123  41.000000
Kuldeep   49      59   74    182  60.666667
Jay       10      89   51    150  50.000000

In [93]:
# 14. Calculate Status (PASS / FAIL) for the Students.


In [94]:
a["status"]=np.where(a["Perc"]>=50,"Pass","fail")
a

DSA  Python  Net  Total       Perc status
Matin     28      96   48    172  57.333333   Pass
Yash       4      69   50    123  41.000000   fail
Kuldeep   49      59   74    182  60.666667   Pass
Jay       10      89   51    150  50.000000   Pass

In [95]:
# 15. Calculate percentage based grade value (per>=90 then A-grade, per>=80 then B-grade,
# per>=70 then C-grade, p#er>=60 then D-grade, per>=50 then E-grade, per<50 then Fgrade)



# 16. Also calculate overall columns total, maximum, minimum and standard deviation for each
# numeric columns

a.describe()


DSA     Python        Net       Total       Perc
count   4.000000   4.000000   4.000000    4.000000   4.000000
mean   22.750000  78.250000  55.750000  156.750000  52.250000
std    20.254629  17.192537  12.230427   26.170913   8.723638
min     4.000000  59.000000  48.000000  123.000000  41.000000
25%     8.500000  66.500000  49.500000  143.250000  47.750000
50%    19.000000  79.000000  50.500000  161.000000  53.666667
75%    33.250000  90.750000  56.750000  174.500000  58.166667
max    49.000000  96.000000  74.000000  182.000000  60.666667

In [96]:
# 17. Display meta-data for each column for the above dataframe.
# 18.Convert the above DataFrame to list within a dictionary.
a.to_dict(orient="list")



{'DSA': [28, 4, 49, 10],
 'Python': [96, 69, 59, 89],
 'Net': [48, 50, 74, 51],
 'Total': [172, 123, 182, 150],
 'Perc': [57.333333333333336, 41.0, 60.666666666666664, 50.0],
 'status': ['Pass', 'fail', 'Pass', 'Pass']}

In [97]:
# 19. Convert this dictionary again to a separate dataframe by adding 500 to each element in product 
a= pd.DataFrame(a)
a["Total"] += 500
a

DSA  Python  Net  Total       Perc status
Matin     28      96   48    672  57.333333   Pass
Yash       4      69   50    623  41.000000   fail
Kuldeep   49      59   74    682  60.666667   Pass
Jay       10      89   51    650  50.000000   Pass

In [98]:
# Task 2
# Using the SF Salaries Dataset from Kaggle! ,complete the tasks outlined in bold below
# 1. Import pandas as pd.
# 2. Read Salaries.csv as a dataframe called sal.
# 3. Check the head of the DataFrame.
# 4. Use the .info() method to find out how many entries there are.
# 5. What is the average BasePay ?
# 6. What is the highest amount of OvertimePay in the dataset ?
# 7. What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer
# that doesn't match up (there is also a lowercase Joseph Driscoll).
# 8. How much does JOSEPH DRISCOLL make (including benefits)?
# 9. What is the name of highest paid person (including benefits)?
# 10. What is the name of lowest paid person (including benefits)? Do you notice something strange
# about how much he or she is paid?
# 11. What was the average (mean) BasePay of all employees per year? (2011-2014) ?
# 12. How many unique job titles are there?
# 13. What are the top 5 most common jobs?
# 14. How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only
# one occurence in 2013?)
# 15. How many people have the word Chief in their job title?
# 16. Is there a correlation between length of the Job Title string and Salary?

In [99]:
# 1. Import pandas as pd.
# 2. Read Salaries.csv as a dataframe called sal.
sal=pd.read_csv('Salaries.csv')
sal

C:\Users\Admin\AppData\Local\Temp\ipykernel_1684\4210438405.py:3: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal=pd.read_csv('Salaries.csv')


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [100]:
# 3. Check the head of the DataFrame.
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [101]:
# 4. Use the .info() method to find out how many entries there are.
sal.info

<bound method DataFrame.info of             Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649             

In [102]:
sal=sal.replace('Not provided',np.nan)
sal=sal.replace('Not Provided',np.nan)


In [103]:
sal['BasePay']=sal['BasePay'].astype('float')

In [104]:
# 5. What is the average BasePay ?
sal['BasePay'].mean()

66325.4488404877

In [105]:
# 6. What is the highest amount of OvertimePay in the dataset ?
sal['OvertimePay']=sal['OvertimePay'].astype('float')
sal["OvertimePay"].max()

245131.88

In [106]:
# 7. What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [107]:
# 8. How much does JOSEPH DRISCOLL make (including benefits)


In [108]:
sal[sal["EmployeeName"]=="JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [109]:


# 15. How many people have the word Chief in their job title?
# 16. Is there a correlation between length of the Job Title string and Salary?

In [110]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25      NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13    106088.18    16452.6      NaN  335279.91         335279.91   
3   77916.00     56120.71   198306.9      NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [111]:
# 9. What is the name of highest paid person (including benefits)?sal["TotalPayBenefits"].max()
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [112]:
# 10. What is the name of lowest paid person (including benefits)? Do you notice something strange
sal[sal["TotalPayBenefits"]==sal["TotalPayBenefits"].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [113]:
# 11. What was the average (mean) BasePay of all employees per year? (2011-2014) ?
sal.groupby("Year").mean("BasePay")

Id       BasePay  OvertimePay      TotalPay  TotalPayBenefits  \
Year                                                                        
2011   18080.0  63595.956517  4531.065429  71744.103871      71744.103871   
2012   54542.5  65436.406857  5023.417824  74113.262265     100553.229232   
2013   91728.5  69630.030216  5281.641980  77611.443142     101440.519714   
2014  129593.0  66564.421924  5401.993737  75463.918140     100250.918884   

      Notes  
Year         
2011    NaN  
2012    NaN  
2013    NaN  
2014    NaN

In [114]:
# 12. How many unique job titles are there?
sal["JobTitle"].nunique()

2158

In [115]:
# 13. What are the top 5 most common jobs?
sal["JobTitle"].value_counts().head(5)


JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [116]:
 #14. How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1) # pretty tricky way to do this...

202

In [135]:
# 15. How many people have the word Chief in their job title?
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False
   

In [116]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25      NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13    106088.18    16452.6      NaN  335279.91         335279.91   
3   77916.00     56120.71   198306.9      NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

In [123]:
ProductsDetails = [(10,"Shampoo",100),
                   (20,"TootPaste",60),
                   (30,"brush",110),
                   (40,"Tub",90),
                  (50,"Bench",150)]
a=pd.DataFrame(ProductsDetails,columns=["ProductId","ProductName","ProductPrice"])
a

ProductId ProductName  ProductPrice
0         10     Shampoo           100
1         20   TootPaste            60
2         30       brush           110
3         40         Tub            90
4         50       Bench           150

In [126]:
a["ProductName"]

0      Shampoo
1    TootPaste
2        brush
3          Tub
4        Bench
Name: ProductName, dtype: object

In [128]:
a.iloc[1]

ProductId              20
ProductName     TootPaste
ProductPrice           60
Name: 1, dtype: object

In [129]:
a.loc[1,"ProductPrice"]

60

In [132]:
a.loc[1:5,["ProductId","ProductName"]]

ProductId ProductName
1         20   TootPaste
2         30       brush
3         40         Tub
4         50       Bench

In [133]:
a.loc[1:4,["ProductPrice"]]

ProductPrice
1            60
2           110
3            90
4           150

In [138]:
m=pd.DataFrame(np.random.randint(0,100,(4,3)),index=["Matin","Yash","Kuldeep","Jay"],columns=["DSA","Python","Net"])

In [143]:
m.loc[m["Python"]<40,"Python"]=41

In [144]:
m

DSA  Python  Net
Matin     40      41   15
Yash      63      41   74
Kuldeep    3      41   33
Jay       88      99   37

In [150]:

m[(m["Python"]>50) & (m["DSA"]>60)]

DSA  Python  Net
Jay   88      99   37

In [153]:
m[m.index.str.startswith("M")]

DSA  Python  Net
Matin   40      41   15

In [155]:
m[m.index.str.endswith("y")]

DSA  Python  Net
Jay   88      99   37

In [161]:
m["total"]=m["Python"]+m["DSA"]+m["Net"]

In [163]:
m["Perc"]=m["total"]/3

In [164]:
m

DSA  Python  Net  total       Perc
Matin     40      41   15     96  32.000000
Yash      63      41   74    178  59.333333
Kuldeep    3      41   33     77  25.666667
Jay       88      99   37    224  74.666667

In [165]:
m["Status"]= np.where(m["Perc"]<40,"Pass","Fail")

In [166]:
m

DSA  Python  Net  total       Perc Status
Matin     40      41   15     96  32.000000   Pass
Yash      63      41   74    178  59.333333   Fail
Kuldeep    3      41   33     77  25.666667   Pass
Jay       88      99   37    224  74.666667   Fail